/*
 *  Copyright (c) 2011, StripBandunk and/or its affiliates. All rights reserved.
 * 
 *       http://stripbandunk.com/
 * 
 *  STRIPBANDUNK PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/*
 * BerandaView.java
 *
 * Created on Nov 22, 2011, 10:34:01 PM
 */
package com.stripbandunk.alexvariasi.view.impl;

import com.stripbandunk.alexvariasi.view.FormApp;
import com.stripbandunk.alexvariasi.view.View;
import javax.swing.JComponent;

/**
 *
 * @author echo
 */
public class BerandaView extends javax.swing.JPanel implements View {

    private static final long serialVersionUID = 1L;

    /** Creates new form BerandaView */
    public BerandaView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void display(FormApp formApp, Object parameter) {
        // do nothing
    }

    @Override
    public JComponent getComponent() {
        return this;
    }
}
