/*
 *  Copyright (c) 2011, StripBandunk and/or its affiliates. All rights reserved.
 * 
 *       http://stripbandunk.com/
 * 
 *  STRIPBANDUNK PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/*
 * DaftarKategoriView.java
 *
 * Created on Nov 22, 2011, 4:44:46 PM
 */
package com.stripbandunk.alexvariasi.view.impl;

import com.stripbandunk.alexvariasi.entity.master.Kategori;
import com.stripbandunk.alexvariasi.manager.SpringManager;
import com.stripbandunk.alexvariasi.service.KategoriService;
import com.stripbandunk.alexvariasi.view.FormApp;
import com.stripbandunk.alexvariasi.view.View;
import com.stripbandunk.jwidget.JDynamicTable;
import com.stripbandunk.jwidget.model.DynamicTableModel;
import java.util.List;
import javax.swing.JComponent;

/**
 *
 * @author Eko Kurniawan Khannedy
 */
public class DaftarKategoriView extends javax.swing.JPanel implements View {

    private static final long serialVersionUID = 1L;

    private FormApp formApp;

    private JDynamicTable jDynamicTable;

    private DynamicTableModel<Kategori> dynamicTableModel;

    /** Creates new form DaftarKategoriView */
    public DaftarKategoriView() {
        initComponents();

        dynamicTableModel = new DynamicTableModel<>(Kategori.class);
        jDynamicTable = new JDynamicTable(dynamicTableModel);
        jScrollPaneTable.setViewportView(jDynamicTable);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar = new javax.swing.JToolBar();
        jButtonTambahKategori = new javax.swing.JButton();
        jButtonUbahKategori = new javax.swing.JButton();
        jButtonHapusKategori = new javax.swing.JButton();
        jScrollPaneTable = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());

        jToolBar.setRollover(true);
        jToolBar.setName("jToolBar"); // NOI18N

        jButtonTambahKategori.setText("Buat Kategori Baru");
        jButtonTambahKategori.setFocusable(false);
        jButtonTambahKategori.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTambahKategori.setName("jButtonTambahKategori"); // NOI18N
        jButtonTambahKategori.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonTambahKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahKategoriActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonTambahKategori);

        jButtonUbahKategori.setText("Ubah Kategori Terseleksi");
        jButtonUbahKategori.setFocusable(false);
        jButtonUbahKategori.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUbahKategori.setName("jButtonUbahKategori"); // NOI18N
        jButtonUbahKategori.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonUbahKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbahKategoriActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonUbahKategori);

        jButtonHapusKategori.setText("Hapus Kategori Terseleksi");
        jButtonHapusKategori.setFocusable(false);
        jButtonHapusKategori.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonHapusKategori.setName("jButtonHapusKategori"); // NOI18N
        jButtonHapusKategori.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonHapusKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusKategoriActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonHapusKategori);

        add(jToolBar, java.awt.BorderLayout.PAGE_START);

        jScrollPaneTable.setName("jScrollPaneTable"); // NOI18N
        add(jScrollPaneTable, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTambahKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahKategoriActionPerformed
        // TODO add your handling code here:
        formApp.showView("tambah-kategori");
    }//GEN-LAST:event_jButtonTambahKategoriActionPerformed

    private void jButtonUbahKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUbahKategoriActionPerformed
        // TODO add your handling code here:
        if (jDynamicTable.getSelectedRow() == -1) {
            formApp.showWarningMessage("Silahkan pilih satu kategori");
        } else {
            int index = jDynamicTable.convertRowIndexToModel(jDynamicTable.getSelectedRow());
            Kategori kategori = dynamicTableModel.get(index);
            formApp.showView("ubah-kategori", kategori);
        }
    }//GEN-LAST:event_jButtonUbahKategoriActionPerformed

    private void jButtonHapusKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusKategoriActionPerformed
        // TODO add your handling code here:
        if (jDynamicTable.getSelectedRow() == -1) {
            formApp.showWarningMessage("Silahkan pilih satu kategori");
        } else {
            int index = jDynamicTable.convertRowIndexToModel(jDynamicTable.getSelectedRow());
            Kategori kategori = dynamicTableModel.get(index);

            KategoriService service = SpringManager.getInstance().getBean(KategoriService.class);
            service.remove(kategori);

            formApp.showInfoMessage("Berhasil menghapus kategori terseleksi");
            display(formApp, null);
        }
    }//GEN-LAST:event_jButtonHapusKategoriActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHapusKategori;
    private javax.swing.JButton jButtonTambahKategori;
    private javax.swing.JButton jButtonUbahKategori;
    private javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JToolBar jToolBar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void display(FormApp formApp, Object parameter) {
        this.formApp = formApp;

        KategoriService kategoriService = SpringManager.getInstance().getBean(KategoriService.class);
        List<Kategori> list = kategoriService.findAll();

        dynamicTableModel.clear();
        for (Kategori kategori : list) {
            dynamicTableModel.add(kategori);
        }
    }

    @Override
    public JComponent getComponent() {
        return this;
    }
}
