/*
 *  Copyright (c) 2011, StripBandunk and/or its affiliates. All rights reserved.
 * 
 *       http://stripbandunk.com/
 * 
 *  STRIPBANDUNK PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/*
 * DaftarPenggunaView.java
 *
 * Created on Nov 23, 2011, 5:27:54 PM
 */
package com.stripbandunk.alexvariasi.view.impl;

import com.stripbandunk.alexvariasi.entity.user.Pengguna;
import com.stripbandunk.alexvariasi.manager.SpringManager;
import com.stripbandunk.alexvariasi.service.PenggunaService;
import com.stripbandunk.alexvariasi.view.FormApp;
import com.stripbandunk.alexvariasi.view.View;
import com.stripbandunk.jwidget.JDynamicTable;
import com.stripbandunk.jwidget.model.DynamicTableModel;
import java.util.List;
import javax.swing.JComponent;

/**
 *
 * @author Eko Kurniawan Khannedy
 */
public class DaftarPenggunaView extends javax.swing.JPanel implements View {

    private static final long serialVersionUID = 1L;

    private JDynamicTable jDynamicTable;

    private DynamicTableModel<Pengguna> dynamicTableModel;

    /** Creates new form DaftarPenggunaView */
    public DaftarPenggunaView() {
        initComponents();

        dynamicTableModel = new DynamicTableModel<>(Pengguna.class);
        jDynamicTable = new JDynamicTable(dynamicTableModel);
        jScrollPane1.setViewportView(jDynamicTable);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        jButton1.setText("Tambah Pengguna Baru");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setName("jButton1"); // NOI18N
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setName("jScrollPane1"); // NOI18N
        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void display(FormApp formApp, Object parameter) {
        PenggunaService penggunaService = SpringManager.getInstance().getBean(PenggunaService.class);
        List<Pengguna> list = penggunaService.findAll();

        dynamicTableModel.clear();
        for (Pengguna pengguna : list) {
            dynamicTableModel.add(pengguna);
        }
    }

    @Override
    public JComponent getComponent() {
        return this;
    }
}
