/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.stripbandunk.alexvariasi.view.impl;

import com.stripbandunk.alexvariasi.entity.transaction.Pembelian;
import com.stripbandunk.alexvariasi.entity.transaction.Penjualan;
import com.stripbandunk.alexvariasi.manager.SpringManager;
import com.stripbandunk.alexvariasi.report.Keuntungan;
import com.stripbandunk.alexvariasi.service.PembelianService;
import com.stripbandunk.alexvariasi.service.PenjualanService;
import com.stripbandunk.alexvariasi.view.DialogView;
import com.stripbandunk.alexvariasi.view.FormApp;
import com.stripbandunk.jwidget.JDynamicTable;
import com.stripbandunk.jwidget.model.DynamicTableModel;
import java.awt.Window;
import java.io.File;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;

/**
 *
 * @author echo
 */
public class LaporanKeuntunganView extends DialogView {

    private JDynamicTable jDynamicTable;

    private DynamicTableModel<Keuntungan> dynamicTableModel;

    private SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");

    private List<Keuntungan> list;

    public LaporanKeuntunganView(FormApp formApp, Date from, Date to) {
        super(formApp);
        initComponents();

        PenjualanService penjualanService = SpringManager.getInstance().getBean(PenjualanService.class);
        PembelianService pembelianService = SpringManager.getInstance().getBean(PembelianService.class);

        List<Penjualan> penjualans = penjualanService.findAll(from, to);
        List<Pembelian> pembelians = pembelianService.findAll(from, to);

        list = new ArrayList<>(penjualans.size() + pembelians.size());

        for (Penjualan penjualan : penjualans) {
            Keuntungan keuntungan = new Keuntungan(penjualan);
            list.add(keuntungan);
        }

        for (Pembelian pembelian : pembelians) {
            Keuntungan keuntungan = new Keuntungan(pembelian);
            list.add(keuntungan);
        }

        Collections.sort(list, new Comparator<Keuntungan>() {

            @Override
            public int compare(Keuntungan o1, Keuntungan o2) {
                return o1.getTanggal().compareTo(o2.getTanggal());
            }
        });

        for (int i = 0; i < list.size(); i++) {
            Keuntungan keuntungan = list.get(i);
            if (i != 0) {
                Keuntungan sebelumnya = list.get(i - 1);
                if (keuntungan.getJenis().equals("Penjualan")) {
                    keuntungan.setKeuntungan(sebelumnya.getKeuntungan() + keuntungan.getTotal());
                } else {
                    keuntungan.setKeuntungan(sebelumnya.getKeuntungan() - keuntungan.getTotal());
                }
            } else {
                if (keuntungan.getJenis().equals("Penjualan")) {
                    keuntungan.setKeuntungan(0 + keuntungan.getTotal());
                } else {
                    keuntungan.setKeuntungan(0 - keuntungan.getTotal());
                }
            }
        }

        dynamicTableModel = new DynamicTableModel<>(list, Keuntungan.class);
        jDynamicTable = new JDynamicTable(dynamicTableModel);
        jScrollPane1.setViewportView(jDynamicTable);

        jLabelJudul.setText("dari tanggal " + dateFormat.format(from) + " sampai " + dateFormat.format(to));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButtonTutup = new javax.swing.JButton();
        jButtonPdf = new javax.swing.JButton();
        jButtonCetak = new javax.swing.JButton();
        jLabelJudul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, 24));
        jLabel1.setText("Laporan Keuntungan");

        jButtonTutup.setText("Tutup");
        jButtonTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTutupActionPerformed(evt);
            }
        });

        jButtonPdf.setText("Simpan (PDF)");
        jButtonPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPdfActionPerformed(evt);
            }
        });

        jButtonCetak.setText("Cetak");
        jButtonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCetakActionPerformed(evt);
            }
        });

        jLabelJudul.setText("Dari Tanggal {} Sampai {}");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCetak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPdf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTutup))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabelJudul))
                        .addGap(0, 347, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTutup)
                    .addComponent(jButtonPdf)
                    .addComponent(jButtonCetak))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTutupActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonTutupActionPerformed

    private void jButtonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCetakActionPerformed
        try {
            InputStream inputStream = LaporanPenjualanView.class.getResourceAsStream("/com/stripbandunk/alexvariasi/report/LaporanKeuntungan.jasper");

            Map<String, Object> map = new HashMap<>();
            JRDataSource dataSource = new JRBeanCollectionDataSource(list);
            map.put(JRParameter.REPORT_DATA_SOURCE, dataSource);
            map.put(JRParameter.REPORT_LOCALE, new Locale("in", "ID"));

            JasperPrint print = JasperFillManager.fillReport(inputStream, map);
            CetakLaporanView view = new CetakLaporanView(getFormApp(), print);
            view.display(LaporanKeuntunganView.this, null);
        } catch (JRException ex) {
            Logger.getLogger(LaporanPenjualanView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCetakActionPerformed

    private void jButtonPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPdfActionPerformed
        try {
            if (jFileChooser1.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                File file = jFileChooser1.getSelectedFile();
                if (!file.getName().endsWith(".pdf")) {
                    file = new File(file.getPath() + ".pdf");
                }
                InputStream inputStream = LaporanPenjualanView.class.getResourceAsStream("/com/stripbandunk/alexvariasi/report/LaporanKeuntungan.jasper");

                Map<String, Object> map = new HashMap<>();
                JRDataSource dataSource = new JRBeanCollectionDataSource(list);
                map.put(JRParameter.REPORT_DATA_SOURCE, dataSource);
                map.put(JRParameter.REPORT_LOCALE, new Locale("in", "ID"));

                JasperPrint print = JasperFillManager.fillReport(inputStream, map);
                JasperExportManager.exportReportToPdfFile(print, file.getPath());
            }
        } catch (JRException ex) {
            Logger.getLogger(LaporanPenjualanView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPdfActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCetak;
    private javax.swing.JButton jButtonPdf;
    private javax.swing.JButton jButtonTutup;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelJudul;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void display(Window formApp, Object parameter) {
        setLocationRelativeTo(formApp);
        setVisible(true);
    }
}
