/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.khannedy.simplepos.view.impl;

import com.github.khannedy.simplepos.entity.master.Pemasok;
import com.github.khannedy.simplepos.entity.transaction.DetailPembelian;
import com.github.khannedy.simplepos.entity.transaction.Pembelian;
import com.github.khannedy.simplepos.entity.user.Pengguna;
import com.github.khannedy.simplepos.manager.LoginManager;
import com.github.khannedy.simplepos.manager.SpringManager;
import com.github.khannedy.simplepos.service.PemasokService;
import com.github.khannedy.simplepos.service.PembelianService;
import com.github.khannedy.simplepos.view.DialogView;
import com.github.khannedy.simplepos.view.FormApp;
import com.stripbandunk.jglasspane.JGlassPane;
import com.stripbandunk.jglasspane.component.MessageComponent;
import com.stripbandunk.jwidget.JDynamicTable;
import com.stripbandunk.jwidget.model.DynamicTableModel;
import java.awt.Window;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import org.springframework.format.number.CurrencyFormatter;

/**
 *
 * @author echo
 */
public class TambahPembelianView extends DialogView {

    private DynamicTableModel<DetailPembelian> dynamicTableModel;

    private JDynamicTable jDynamicTable;

    private JGlassPane jGlassPane;

    private MessageComponent messageComponent;

    private long total;

    public TambahPembelianView(FormApp formApp) {
        super(formApp);
        initComponents();

        dynamicTableModel = new DynamicTableModel<>(DetailPembelian.class);
        jDynamicTable = new JDynamicTable(dynamicTableModel);
        jScrollPane1.setViewportView(jDynamicTable);

        jGlassPane = new JGlassPane();
        setGlassPane(jGlassPane);
        getGlassPane().setVisible(true);

        messageComponent = new MessageComponent();
        jGlassPane.addGlassPaneComponent(messageComponent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPengguna = new javax.swing.JTextField();
        jTextFieldTanggal = new javax.swing.JTextField();
        jTextFieldKodePemasok = new javax.swing.JTextField();
        jTextFieldNamaPemasok = new javax.swing.JTextField();
        jButtonCari = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButtonBatal = new javax.swing.JButton();
        jButtonBayar = new javax.swing.JButton();
        jButtonTambahBarang = new javax.swing.JButton();
        jButtonHapusBarang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, 24));
        jLabel1.setText("Transaksi Pembelian");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Transaksi"));

        jLabel2.setText("Pengguna :");

        jLabel3.setText("Tanggal :");

        jLabel4.setText("Kode Pemasok :");

        jLabel5.setText("Nama Pemasok :");

        jTextFieldPengguna.setEnabled(false);

        jTextFieldTanggal.setEnabled(false);

        jTextFieldNamaPemasok.setEnabled(false);

        jButtonCari.setText("Cari");
        jButtonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPengguna)
                    .addComponent(jTextFieldTanggal)
                    .addComponent(jTextFieldNamaPemasok)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldKodePemasok, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCari)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldKodePemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldNamaPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Total Harga"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabelTotal.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jLabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotal.setText("Rp. 1.000.000.000");
        jLabelTotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.add(jLabelTotal, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jButtonBatal.setText("Batal");
        jButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalActionPerformed(evt);
            }
        });

        jButtonBayar.setText("Simpan");
        jButtonBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBayarActionPerformed(evt);
            }
        });

        jButtonTambahBarang.setText("Tambah Barang");
        jButtonTambahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahBarangActionPerformed(evt);
            }
        });

        jButtonHapusBarang.setText("Hapus Barang");
        jButtonHapusBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonTambahBarang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHapusBarang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBayar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBatal)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBatal)
                    .addComponent(jButtonBayar)
                    .addComponent(jButtonTambahBarang)
                    .addComponent(jButtonHapusBarang))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonBatalActionPerformed

    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
        CariPemasokView cariPemasok = new CariPemasokView(getFormApp());
        Pemasok pelanggan = cariPemasok.search(this);
        if (pelanggan != null) {
            jTextFieldKodePemasok.setText(pelanggan.getId());
            jTextFieldNamaPemasok.setText(pelanggan.getNama());
        }
    }//GEN-LAST:event_jButtonCariActionPerformed

    private void jButtonTambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahBarangActionPerformed
        TambahBarangPembelianView tambahBarangPembelianView = new TambahBarangPembelianView(getFormApp());
        DetailPembelian detailPembelian = tambahBarangPembelianView.search(this);
        if (detailPembelian != null) {
            for (int i = 0; i < dynamicTableModel.getRowCount(); i++) {
                DetailPembelian item = dynamicTableModel.get(i);
                if (item.getDetailBarang().getId().equals(detailPembelian.getDetailBarang().getId())) {
                    detailPembelian.setJumlah(item.getJumlah() + detailPembelian.getJumlah());
                    dynamicTableModel.remove(i);
                    break;
                }
            }
            dynamicTableModel.add(detailPembelian);
            total();
        }
    }//GEN-LAST:event_jButtonTambahBarangActionPerformed

    private void jButtonHapusBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusBarangActionPerformed
        if (jDynamicTable.getSelectedRow() == -1) {
            messageComponent.showWarning("Pilih salah satu");
        } else {
            dynamicTableModel.remove(jDynamicTable.convertRowIndexToModel(jDynamicTable.getSelectedRow()));
            total();
        }
    }//GEN-LAST:event_jButtonHapusBarangActionPerformed

    private void jButtonBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBayarActionPerformed
        PemasokService pelangganService = SpringManager.getInstance().getBean(PemasokService.class);
        PembelianService pembelianService = SpringManager.getInstance().getBean(PembelianService.class);

        Pemasok pemasok = pelangganService.find(jTextFieldKodePemasok.getText());
        if (pemasok == null) {
            messageComponent.showWarning("Pemasok Tidak Ditemukan");
        } else if (dynamicTableModel.getRowCount() == 0) {
            messageComponent.showWarning("Belum ada barang yang dibeli");
        } else {
            Pembelian pembelian = new Pembelian();
            pembelian.setPemasok(pemasok);
            pembelian.setPengguna(LoginManager.getInstance().getPengguna());
            pembelian.setWaktuTransaksi(new Date());
            pembelian.setWaktuTransaksiDiubah(new Date());
            for (int i = 0; i < dynamicTableModel.getRowCount(); i++) {
                DetailPembelian detailPembelian = dynamicTableModel.get(i);
                pembelian.tambahDetailPembelian(detailPembelian);
            }

            pembelianService.save(pembelian);
            dispose();
        }
    }//GEN-LAST:event_jButtonBayarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonBayar;
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonHapusBarang;
    private javax.swing.JButton jButtonTambahBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldKodePemasok;
    private javax.swing.JTextField jTextFieldNamaPemasok;
    private javax.swing.JTextField jTextFieldPengguna;
    private javax.swing.JTextField jTextFieldTanggal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void display(Window formApp, Object parameter) {
        total();

        jTextFieldTanggal.setText(dateFormat.format(new Date()));
        Pengguna pengguna = LoginManager.getInstance().getPengguna();
        if (pengguna != null) {
            jTextFieldPengguna.setText(pengguna.getKaryawan().getNama());
        }

        setLocationRelativeTo(formApp);
        setVisible(true);
    }

    private CurrencyFormatter formatter = new CurrencyFormatter();

    private Locale locale = new Locale("in", "ID");

    private SimpleDateFormat dateFormat = new SimpleDateFormat("dd MMMM yyyy");

    private void total() {
        total = 0l;
        for (int i = 0; i < dynamicTableModel.getRowCount(); i++) {
            DetailPembelian detailPembelian = dynamicTableModel.get(i);
            total += detailPembelian.getSubTotal();
        }
        formatter.setFractionDigits(0);
        jLabelTotal.setText(formatter.print(total, locale));
    }
}
